# Site settings
title: Emulation Resources
name: Emulation Resources
description: "Site that contains lists of different emulator divided by system"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
