# Site settings
title: Emulation Resources
  name: Emulation-Resources
description: "Site that contains list of different emulator per system"

# Build settings
remote_theme: cotes2020/jekyll-theme-chirpy
