# Site settings
title: Emulation Resources
name: Emulation Resources
description: "Site that contains list of different emulator per system"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
